Resolve namespace for plugin type 'interface', instead of using %module placeholder
drupal-code-builder/drupal-code-builder pull request #216
Opened 2020-10-31 16:56 UTC by jedihe

2020-11-01 07:23 UTC, joachim-n requested changes
Thanks for working on this!

There's a few things that need tweaking. I'm happy to merge and do it myself or let you do it; let me know what you prefer :)

2020-11-01 07:23 UTC, joachim-n commented on Generator/PHPFile.php
> +      $module_name = end($current_namespace_pieces);
That's not always the case. $current_namespace_pieces could be ['Drupal',  'mymodule', 'Plugin', 'Block'] for instance.

But we don't need the generated module name here to match on in the regex anyway! It's a module name so it will match the \w+ that represents an existing module's name.

So we can just simplify the regex by removing the alternation.

2020-11-01 07:23 UTC, joachim-n commented on Generator/PHPFile.php
> +      sort($imported_classes, SORT_NATURAL | SORT_FLAG_CASE);
Might be clearer to use natcasesort() here?

2020-11-01 07:23 UTC, joachim-n commented on Generator/PHPFile.php
> +      // Allow a match of $module_name for a namespace piece, for cases where we
This line should just be removed.

2020-11-01 07:23 UTC, joachim-n commented on Generator/PHPFile.php
> +      // Allow a match of $module_name for a namespace piece, for cases where we
But we should add docs to the method to say that tokens should not be used in fully-qualified class names, because of the sorting.

2020-11-01 07:23 UTC, joachim-n commented on Test/Unit/ComponentPluginType8Test.php
> +    $module_name = 'a_test_module';
The change in test module name doesn't seem related?

2020-11-01 07:23 UTC, joachim-n commented on Test/Unit/Parsing/PHPTester.php
> +  public function assertImportsSorted($message = NULL) {
This new test assertion is really nice!!

2020-11-02 12:46 UTC, jedihe commented
Cool! let me try fixing it.

2020-11-02 12:58 UTC, jedihe commented on Generator/PHPFile.php
> +      $module_name = end($current_namespace_pieces);
Done!

2020-11-02 13:00 UTC, jedihe commented on Test/Unit/ComponentPluginType8Test.php
> +    $module_name = 'a_test_module';
test_module alone doesn't really require natcasesort() to change the order for this specific test-case, so I thought it would be better to actually detect if such sorting is taking place.

2020-11-02 13:00 UTC, jedihe commented on Test/Unit/Parsing/PHPTester.php
> +  public function assertImportsSorted($message = NULL) {
:smile:

2020-11-07 13:10 UTC, merged

2020-11-07 13:16 UTC, joachim-n commented on Test/Unit/ComponentPluginType8Test.php
> +    $module_name = 'a_test_module';
Oh, good point! I hadn't realised that was what it was for.

2020-11-07 13:17 UTC, joachim-n commented
Great, thanks!

I'll have a look at this soon.

I need to take care of this TODO:

> +      // Sort the imported classes. todo sort AFTER removing the \\ !!

and clean up my initial messy commits!

2020-11-07 13:53 UTC, jedihe commented
Great! :smile: